apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-postfix-secure-config"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
  {{- range $key, $val := .Values.postfix.secureConfigs }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
